### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by daarxwalker** [tomblachut/svelte-intellij#124]
Do you have any roadmap or plans about TypeScript support for the plugin? It's only blocker for develop with TS now.

#32 I know about this thread, but it looks dead.

Thanks!

**Comment by bradak1** [comment]
https://svelte.dev/blog/svelte-and-typescript
any updates?

**Comment by Atulin** [comment]
Looking at the owner's activity on Github, it'll be a while.

Oh well, VS Code, here I come.

**Comment by tomblachut** [comment]
Folks I'm closing this one in favor of #32.
Please don't create new issues even if old ones look "dead" because I've "resurrected" a couple times before already as I'm sure many of you also did when running a side project.

@Atulin nobody cares given your entitled tone. Nevertheless I wish you all the best in your future endeavors.
