### ISSUE TITLE
0.13.0 not available in Jetbrains Marketplace. Download version not compatible with 2020.3 EAP

### ISSUE THREAD

**Issue by btakita** [tomblachut/svelte-intellij#161]
I was notified about a Svelte plugin upgrade from WebStorm. I attempted the upgrade & the Svelte plugin got downgraded to v0.12.1. v0.12.1 is incompatible with WebStorm 2020.3 EAP. I uninstalled v0.12.1 & then attempted to reinstall from the Marketplace. Only v0.12.1 is available. v0.13.0 is nowhere to be found.

I then downloaded the zip file from the github page releases. When attempting to install, the error `Plugin 'Svelte' (version 0.13.0) was explicitly marked as incompatible with the current version of the IDE` occurred.

**Comment by tomblachut** [comment]
I've marked 0.13 and 0.12.2 as incompatible, because some APIs has changed and Svelte plugin is not yet updated for them - IDE throws errors and it's misleading.

I forgot about 0.12.1, sorry about the confusion - I also marked is as incompatible so now nothing should work as expected.

EAP is not a stable product, you should use 2020.2 for now.
